### ISSUE TITLE
Epic: dealing with myriad remote access tools

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#154]
We have many ways to access our resources.

- [X] `ssh` `workflow_solutions/ssh.md`
- [X] `scp` `workflow_solutions/ssh.md`
- [x] `sftp` `workflow_solutions/ssh.md`
- [x] Open OnDemand https://rc.uab.edu
- [x] https://cloud.rc.uab.edu
- [x] FileZilla
- [x] Globus
- [ ] VNC
- [ ] MobaXTerm

Let's decide which of these we want to support with documentation and which we do not want to support.

I would like to see a catch-all page with a matrix of options. Rows would be access methods (above), columns would be services we provide (Cheaha, cloud.rc, k8s). If it is possible to use an interface with a service, there would be a link in that cell, otherwise no link.

Then we would have one page (or section) for each service, and the link would send them to the appropriate entry point for that service.

**Comment by wwarriner** [comment]
I've checked off the one we do want to support. I'm comfortable not supporting VNC nor MobaXTerm. I'm going to close this issue as complete.
