### ISSUE TITLE
Reorganize and fill out TOC 

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#254]
Epic for reorganizing and filling out the TOC.

First step is to update the TOC and build stubs.
Then we can fill out the stubs (see linked issues below)

Existing related issues (not all of these should be closed when this is finished!!)

- [x] Add policies stub section to docs TOC #228 
- [x] Grant and Publication Resources #213 
- [x] Create and use Environment Management section #185 
- [x] Add resources for Git #132
- [x] Containerization page #88 
- [x] Add Granting Resources docs #43 
- [x] Add Gitlab documentation #38 
- [x] Consistent naming scheme #24

**Comment by bjoyce3** [comment]
Added first step PR: https://github.com/uabrc/uabrc.github.io/pull/255

**Comment by wwarriner** [comment]
All of the relevant issues are closed. Closing this.
